apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-namespace
spec:
  type: NodePort
  ports:
    - port: 31573
      targetPort: 31573
      protocol: TCP
  selector:
    app: minio